id: P009262
initial_creation_type: ocr
source_metadata:
  id: bdr:W18133
  title: ཀརྨ་པ་སྐུ་ཕྲེང་རིམ་བྱོན་གྱི་མཛད་རྣམ
  author: ''
  volumes:
    dec714e8ffe8470bb91e44e406128879:
      image_group_id: I1PD36385
      title: ''
      volume_number: 1
      total_pages: 258
